let dados = [
    {
        imagem: "mercurio.png",
        titulo: "1º Mercúrio",
        descricao: "Mercúrio é o planeta mais próximo do Sol e o menor do Sistema Solar.<br> Tem um diâmetro de cerca de 4.880 km e é composto principalmente de ferro e níquel, com um núcleo metálico grande. <br>Sua superfície é repleta de crateras e planícies, similar à da Lua, devido à falta de atmosfera significativa. <br>As temperaturas em Mercúrio variam extremamente, de cerca de -180°C à noite a 430°C durante o dia, devido à sua atmosfera muito fina.<br> O planeta tem uma rotação lenta, levando cerca de 59 dias terrestres para completar uma volta em torno de seu eixo, e uma órbita rápida de 88 dias terrestres ao redor do Sol.<br> Mercúrio possui um campo magnético fraco, que cria uma magnetosfera ao seu redor, e foi explorado pela sonda Mariner 10 na década de 1970 e pela sonda MESSENGER da NASA, que orbitou o planeta de 2011 a 2015.",
        link: "https://youtu.be/huGvInnMwIY?si=_MJOtXpGSHTO5831",
    },
    {
        titulo: "2º Vênus",
        imagem: "venus.png",
        descricao: "Vênus é o segundo planeta do Sistema Solar, situado entre Mercúrio e a Terra. <br>Tem um diâmetro de aproximadamente 12.104 km, o que o faz um pouco menor que a Terra.<br> O planeta é conhecido por sua densa atmosfera composta principalmente de dióxido de carbono, com nuvens espessas de ácido sulfúrico, tornando-o o planeta mais quente do Sistema Solar, com temperaturas na superfície que podem chegar a 465°C.<br> A superfície de Vênus é coberta por vastos campos de lava e possui muitas montanhas e planícies, além de um grande número de vulcões.<br> A pressão atmosférica na superfície é cerca de 90 vezes a da Terra, equivalente à pressão encontrada a 900 metros abaixo da superfície dos oceanos terrestres.<br> Vênus tem um dia muito longo, com uma rotação lenta e retrógrada que leva cerca de 243 dias terrestres para completar uma volta em torno de seu eixo.<br> Curiosamente, um dia em Vênus (o tempo que leva para girar sobre seu eixo) é mais longo que um ano venusiano, que é de aproximadamente 225 dias terrestres.<br> Além disso, Vênus tem um movimento de rotação retrógrado, ou seja, gira no sentido oposto ao dos outros planetas.<br> O planeta também possui um efeito estufa extremo, que faz com que a temperatura na superfície seja quente o suficiente para derreter chumbo.<br> Apesar de sua aparência brilhante no céu, devido às nuvens refletivas, a superfície de Vênus é inóspita e difícil de explorar. <br>As missões de exploração, como as da sonda Venera da União Soviética, forneceram informações valiosas, mas a atmosfera densa e quente representa um grande desafio para a exploração contínua.",
        link: "https://youtu.be/M11f_041080?si=ziFPHS6Jb1iiDQuP",
    },
    {
        titulo: "3º Terra",
        imagem: "terra.png",
        descricao: "A Terra é o terceiro planeta do Sistema Solar e o único conhecido por abrigar vida.<br> Com um diâmetro de cerca de 12.742 km, é o quinto maior planeta do Sistema Solar.<br> Sua atmosfera é composta principalmente de nitrogênio (78%) e oxigênio (21%), com pequenas quantidades de outros gases como argônio e dióxido de carbono. <br> A Terra possui uma superfície diversificada, incluindo oceanos, continentes, montanhas, desertos e florestas. <br> Cerca de 71% da superfície do planeta é coberta por água, principalmente oceanos, e o restante é composto por terras emergidas, como continentes e ilhas. <br> O planeta tem um clima variado, com zonas temperadas, tropicais e polares, e o clima é regulado por um complexo sistema de circulação atmosférica e oceânica. <br> As mudanças climáticas, tanto naturais quanto influenciadas por atividades humanas, têm um impacto significativo na biosfera e no clima da Terra.<br> A Terra leva aproximadamente 365,25 dias para completar uma órbita ao redor do Sol, o que define o ano terrestre. Além disso, um dia na Terra, ou seja, o tempo necessário para uma rotação completa em torno de seu eixo, é de 24 horas.<br> A inclinação do eixo da Terra em relação ao plano de sua órbita ao redor do Sol causa as estações do ano.<br> O planeta possui um campo magnético gerado pelo movimento de ferro líquido no seu núcleo, que protege a superfície de radiações solares e cósmicas prejudiciais.<br> A presença de água líquida, uma atmosfera estável e uma gama de temperaturas relativamente moderadas são alguns dos fatores que fazem da Terra um ambiente propício para a vida.<br> A Terra também é o lar da biodiversidade, com milhões de espécies de plantas, animais e microrganismos, e possui uma rica variedade de ecossistemas.<br> A exploração espacial e as tecnologias avançadas têm proporcionado uma compreensão mais profunda do nosso planeta e seu lugar no universo.",
        link: "https://youtu.be/cnMWTVsQV-k?si=6vK89rn5IGh7Y5be",
    },
    {
        titulo: "4º Marte",
        imagem: "marte.png",
        descricao: "Marte é o quarto planeta do Sistema Solar, situado entre a Terra e Júpiter.<br> Conhecido como o Planeta Vermelho devido à sua superfície rica em óxido de ferro, Marte tem um diâmetro de aproximadamente 6.779 km, cerca de metade do tamanho da Terra.<br> A atmosfera marciana é muito fina e composta principalmente de dióxido de carbono (95%), com pequenas quantidades de nitrogênio e argônio. <br>A superfície de Marte apresenta uma variedade de características geológicas, incluindo vastos desertos, enormes vulcões, como o Olympus Mons, que é o maior vulcão do Sistema Solar, e o Valles Marineris, um sistema de cânions que se estende por mais de 4.000 km.<br> Além disso, Marte possui calotas polares compostas de água e dióxido de carbono congelado.<br> As temperaturas em Marte são bastante frias, variando entre cerca de -125°C nos polos durante o inverno e até 20°C no equador durante o verão.<br> A pressão atmosférica na superfície é menos de 1% da pressão atmosférica da Terra, o que contribui para a sensação de frio e a dificuldade em manter água líquida na superfície. Marte tem uma rotação similar à da Terra, com um dia marciano (ou sol) tendo cerca de 24,6 horas.<br> No entanto, sua órbita ao redor do Sol é mais elíptica do que a da Terra, o que faz com que as estações do ano sejam mais extremas.<br> Um ano marciano dura aproximadamente 687 dias terrestres.<br> O campo magnético de Marte é muito fraco, o que resulta em uma proteção insuficiente contra radiações solares e cósmicas.<br> Isso contribui para a perda gradual de sua atmosfera ao longo de bilhões de anos. <br>Explorações de Marte têm sido conduzidas por várias missões espaciais, como os rovers Spirit, Opportunity, Curiosity e Perseverance, que têm fornecido informações valiosas sobre a geologia e a potencial habitabilidade do planeta.<br> O interesse em Marte é grande devido à sua semelhança com a Terra e ao potencial para futuras missões de exploração e até colonização.",
        link: "https://youtu.be/JsjkzTIByks?si=H2VmaUcGwiWpoYEB",
    },
    {
        titulo: "5º Júpiter",
        imagem: "jupiter.png",
        descricao: "Júpiter é o maior planeta do Sistema Solar, com um diâmetro de cerca de 139.820 km, mais de 11 vezes o diâmetro da Terra.<br> É um gigante gasoso composto principalmente de hidrogênio e hélio, com uma atmosfera caracterizada por suas bandas distintas e por um sistema complexo de nuvens e tempestades. <br>Uma das características mais notáveis de Júpiter é a Grande Mancha Vermelha, uma enorme tempestade anticiclônica que é visível em seu hemisfério sul e tem aproximadamente três vezes o tamanho da Terra.<br> Além disso, Júpiter exibe uma série de bandas atmosféricas chamadas de cinturões e zonas, que resultam da rápida rotação do planeta e de sua dinâmica atmosférica.<br> Júpiter tem uma rotação extremamente rápida, completando uma volta em torno de seu eixo em cerca de 10 horas, o que resulta em um achatamento significativo em seus polos.<br> Um ano em Júpiter, ou seja, o tempo que leva para orbitar o Sol, dura aproximadamente 12 anos terrestres.<br> O planeta tem um campo magnético extremamente forte, o maior do Sistema Solar, que gera uma magnetosfera muito extensa, capaz de criar intensas auroras em suas regiões polares.<br> Júpiter também possui um sistema de anéis fracos, que são compostos principalmente de partículas de poeira.<br> Júpiter é rodeado por um grande número de luas, com mais de 90 conhecidas até o momento.<br> As quatro maiores, chamadas de luas galileanas — Ío, Europa, Ganimedes e Calisto — foram descobertas por Galileu Galilei em 1610. Cada uma dessas luas tem características únicas, como vulcões ativos em Ío e um possível oceano de água líquida sob a superfície de Europa.<br> Missões espaciais como a Juno, que está atualmente em órbita ao redor de Júpiter, têm fornecido informações valiosas sobre a composição e a dinâmica do planeta.<br> A exploração contínua de Júpiter e suas luas pode revelar mais sobre a formação do Sistema Solar e a potencial habitabilidade em outros locais do Sistema Solar.",
        link: "https://youtu.be/sJMhnBZLEaE?si=vfiMsbSFbxJWkATB",
    },
    {
        titulo: "6º Saturno",
        imagem: "saturno.png",
        descricao: "Saturno é o segundo maior planeta do Sistema Solar e é conhecido por seus impressionantes anéis.<br> Com um diâmetro de aproximadamente 116.460 km, Saturno é um gigante gasoso composto principalmente de hidrogênio e hélio.<br> Seus anéis são compostos principalmente de partículas de gelo e rocha e se estendem por milhares de quilômetros ao redor do planeta, embora tenham apenas alguns quilômetros de espessura.<br> O sistema de anéis de Saturno é composto por vários anéis distintos, designados por letras como A, B e C, além de vários anéis menores e mais tênues. <br>Saturno tem uma rotação rápida, completando uma volta em torno de seu eixo em cerca de 10,7 horas, e um ano em Saturno dura aproximadamente 29,5 anos terrestres.<br> A atmosfera de Saturno apresenta bandas e tempestades, semelhante a Júpiter, mas com menos contraste e menos nuvens visíveis.<br> O planeta possui um campo magnético robusto e uma magnetosfera que cria intensas auroras em suas regiões polares.<br> Saturno é acompanhado por uma grande quantidade de luas, com mais de 80 conhecidas. <br>A maior lua de Saturno, Titã, é maior que o planeta Mercúrio e possui uma atmosfera densa composta principalmente de nitrogênio e metano.<br> Titã é uma das luas mais intrigantes devido à sua possível presença de lagos de metano líquido e uma superfície variada.<br> Outras luas notáveis incluem Encélado, que tem gêiseres de água que podem indicar um oceano subsuperficial, e Mimas, conhecida por sua grande cratera.<br> A exploração de Saturno e suas luas tem sido realizada por missões como a Cassini-Huygens, que forneceu uma grande quantidade de dados sobre o planeta, seus anéis e suas luas durante seu tempo em órbita, de 2004 a 2017.",
        link: "https://youtu.be/GY4j6R6Mv2s?si=CO6eEaQlalw2xPKs",
    },
    {
        titulo: "7º Urano",
        imagem: "urano.png",
        descricao: "Urano é o sétimo planeta do Sistema Solar, conhecido por sua cor azulada devido ao metano em sua atmosfera.<br> Com um diâmetro de aproximadamente 50.724 km, Urano é um gigante gasoso composto principalmente de hidrogênio, hélio e metano.<br> A atmosfera de Urano é uma mistura de hidrogênio e hélio, com uma camada de metano que absorve a luz vermelha e reflete a luz azul, dando ao planeta sua cor característica.<br> Urano é único entre os planetas do Sistema Solar por ter um eixo de rotação altamente inclinado, quase paralelo ao plano de sua órbita.<br> Isso faz com que seus polos estejam quase voltados para o Sol, resultando em extremos sazonais em seus climas.<br> Um dia em Urano, ou seja, o tempo necessário para uma rotação completa, é de cerca de 17,9 horas, enquanto um ano uraniano dura aproximadamente 84 anos terrestres.<br> O planeta possui um campo magnético peculiar, inclinado em relação ao seu eixo de rotação e deslocado do centro do planeta.<br> Urano tem um sistema de anéis fracos e estreitos, e suas luas são várias e variadas.<br> A maior lua de Urano é Titania, seguida por outras como Oberon, Umbriel, Ariel e Miranda. <br>A exploração de Urano foi realizada pela sonda Voyager 2 da NASA em 1986, que forneceu as primeiras e únicas imagens detalhadas do planeta e suas luas.<br> Urano é um planeta de interesse para futuras missões devido à sua atmosfera única e seus aspectos incomuns de rotação.",
        link: "https://youtu.be/qV8NueymSfQ?si=7vXayEdis4lI5HFH",
    },
    {
        titulo: "8º Netuno",
        imagem: "Netuno.png",
        descricao: "Netuno é o oitavo e último planeta do Sistema Solar, situado além de Urano.<br> Com um diâmetro de aproximadamente 49.244 km, Netuno é um gigante gasoso composto principalmente de hidrogênio, hélio e metano.<br> O metano em sua atmosfera absorve a luz vermelha e reflete a luz azul, dando a Netuno sua cor azul vibrante. <br>Netuno é conhecido por suas intensas tempestades e ventos fortes, que podem atingir velocidades superiores a 2.000 km/h.<br> A Grande Mancha Escura, uma enorme tempestade anticiclônica, é uma das características atmosféricas mais notáveis de Netuno.<br> O planeta tem um campo magnético inclinado e deslocado em relação ao centro do planeta, semelhante ao de Urano, e um sistema de anéis fracos.<br> Netuno possui um sistema de luas, com a maior delas sendo Tritão, que é uma lua geologicamente ativa com gêiseres de nitrogênio.<br> Tritão é uma das poucas luas no Sistema Solar que orbita seu planeta em uma direção retrógrada, o que sugere que pode ter sido capturada pela gravidade de Netuno.<br> Netuno leva aproximadamente 16 horas para completar uma rotação em torno de seu eixo, e um ano em Netuno dura cerca de 165 anos terrestres.<br> O planeta foi explorado pela sonda Voyager 2 da NASA em 1989, que forneceu as primeiras imagens detalhadas e informações sobre Netuno e suas luas.",
        link: "https://youtu.be/R1o1GIOZZYk?si=VU1v1wKKBSm84G0b",
    },
];
